<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DataRowsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('data_rows')->delete();
        
        \DB::table('data_rows')->insert(array (
            0 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'ID',
                'edit' => 0,
                'field' => 'id',
                'id' => 1,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'number',
            ),
            1 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Name',
                'edit' => 1,
                'field' => 'name',
                'id' => 2,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            2 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Email',
                'edit' => 1,
                'field' => 'email',
                'id' => 3,
                'order' => 3,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            3 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Password',
                'edit' => 1,
                'field' => 'password',
                'id' => 4,
                'order' => 4,
                'read' => 0,
                'required' => 1,
                'type' => 'password',
            ),
            4 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Remember Token',
                'edit' => 0,
                'field' => 'remember_token',
                'id' => 5,
                'order' => 5,
                'read' => 0,
                'required' => 0,
                'type' => 'text',
            ),
            5 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 6,
                'order' => 6,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            6 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 7,
                'order' => 7,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            7 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Avatar',
                'edit' => 1,
                'field' => 'avatar',
                'id' => 8,
                'order' => 8,
                'read' => 1,
                'required' => 0,
                'type' => 'image',
            ),
            8 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '{"scope":"roles","model":"App\\\\Models\\\\Role","table":"roles","type":"belongsTo","column":"role_id","key":"id","label":"display_name","pivot_table":"roles","pivot":"0","taggable":"0"}',
                'display_name' => 'Role',
                'edit' => 1,
                'field' => 'user_belongsto_role_relationship',
                'id' => 9,
                'order' => 10,
                'read' => 1,
                'required' => 0,
                'type' => 'relationship',
            ),
            9 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '{"scope":"roles","model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsToMany","column":"id","key":"id","label":"display_name","pivot_table":"user_roles","pivot":"1","taggable":"0"}',
                'display_name' => 'Roles',
                'edit' => 1,
                'field' => 'user_belongstomany_role_relationship',
                'id' => 10,
                'order' => 11,
                'read' => 1,
                'required' => 0,
                'type' => 'relationship',
            ),
            10 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Settings',
                'edit' => 0,
                'field' => 'settings',
                'id' => 11,
                'order' => 12,
                'read' => 0,
                'required' => 0,
                'type' => 'hidden',
            ),
            11 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 2,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'ID',
                'edit' => 0,
                'field' => 'id',
                'id' => 12,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'number',
            ),
            12 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 2,
                'delete' => 1,
                'details' => NULL,
                'display_name' => 'Name',
                'edit' => 1,
                'field' => 'name',
                'id' => 13,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            13 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 2,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'Created At',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 14,
                'order' => 3,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            14 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 2,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 15,
                'order' => 4,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            15 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'ID',
                'edit' => 0,
                'field' => 'id',
                'id' => 16,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'number',
            ),
            16 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 3,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Name',
                'edit' => 1,
                'field' => 'name',
                'id' => 17,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            17 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 18,
                'order' => 3,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            18 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 19,
                'order' => 4,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            19 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 3,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Display Name',
                'edit' => 1,
                'field' => 'display_name',
                'id' => 20,
                'order' => 5,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            20 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Role',
                'edit' => 1,
                'field' => 'role_id',
                'id' => 21,
                'order' => 9,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            21 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Email Verified At',
                'edit' => 1,
                'field' => 'email_verified_at',
                'id' => 22,
                'order' => 6,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            22 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 4,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => 0,
                'field' => 'id',
                'id' => 23,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            23 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 4,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|min:1|max:50","messages":{"required":"El campo nombre es requerido.","max":"Se permite hasta 50 caracteres en el campo nombre","min":"Debe ingresar un nombre mayor de un caracter"}}}',
                'display_name' => 'Nombre',
                'edit' => 1,
                'field' => 'name',
                'id' => 24,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            24 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 4,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Tipo',
                'edit' => 1,
                'field' => 'type',
                'id' => 25,
                'order' => 3,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            25 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 4,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Creado',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 27,
                'order' => 7,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            26 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 4,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Editado',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 28,
                'order' => 8,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            27 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 5,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => 0,
                'field' => 'id',
                'id' => 29,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            28 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 5,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|min:1|max:50","messages":{"required":"El campo nombre es requerido.","max":"Se permite hasta 50 caracteres en el campo nombre","min":"Debe ingresar un nombre mayor de un caracter"}}}',
                'display_name' => 'Nombre',
                'edit' => 1,
                'field' => 'name',
                'id' => 30,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            29 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 5,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Creado',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 31,
                'order' => 3,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            30 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 5,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Editado',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 32,
                'order' => 4,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            31 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 4,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\TypeRoom","table":"type_rooms","type":"belongsTo","column":"type","key":"id","label":"name","pivot_table":"commands","pivot":"0","taggable":"0"}',
                'display_name' => 'Tipo',
                'edit' => 1,
                'field' => 'room_belongsto_type_room_relationship',
                'id' => 33,
                'order' => 5,
                'read' => 1,
                'required' => 1,
                'type' => 'relationship',
            ),
            32 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 4,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Status","table":"statuses","type":"belongsTo","column":"status_id","key":"id","label":"name","pivot_table":"commands","pivot":"0","taggable":"0"}',
                'display_name' => 'Estatus',
                'edit' => 0,
                'field' => 'room_belongsto_status_relationship',
                'id' => 34,
                'order' => 6,
                'read' => 1,
                'required' => 0,
                'type' => 'relationship',
            ),
            33 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 4,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Status Id',
                'edit' => 0,
                'field' => 'status_id',
                'id' => 35,
                'order' => 4,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            34 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 6,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'N°',
                'edit' => 0,
                'field' => 'id',
                'id' => 36,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            35 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Paciente',
                'edit' => 1,
                'field' => 'patient',
                'id' => 37,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            36 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Dirección',
                'edit' => 1,
                'field' => 'address',
                'id' => 38,
                'order' => 3,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            37 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Fecha de ingreso',
                'edit' => 1,
                'field' => 'date_admission',
                'id' => 39,
                'order' => 4,
                'read' => 1,
                'required' => 1,
                'type' => 'timestamp',
            ),
            38 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Fecha de egreso',
                'edit' => 1,
                'field' => 'date_agress',
                'id' => 40,
                'order' => 16,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            39 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Diagnóstico',
                'edit' => 1,
                'field' => 'diagnostic',
                'id' => 41,
                'order' => 5,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            40 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Doctor',
                'edit' => 1,
                'field' => 'doctor',
                'id' => 42,
                'order' => 6,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            41 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{}',
            'display_name' => 'Enfermera (o)',
                'edit' => 1,
                'field' => 'nurse',
                'id' => 43,
                'order' => 7,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            42 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Medico en turno',
                'edit' => 1,
                'field' => 'doctor_shift',
                'id' => 44,
                'order' => 8,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            43 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Tipo',
                'edit' => 1,
                'field' => 'type',
                'id' => 45,
                'order' => 9,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            44 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Estatus',
                'edit' => 1,
                'field' => 'status_id',
                'id' => 46,
                'order' => 10,
                'read' => 0,
                'required' => 1,
                'type' => 'text',
            ),
            45 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Creado',
                'edit' => 1,
                'field' => 'created_at',
                'id' => 47,
                'order' => 11,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            46 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 6,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Editado',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 48,
                'order' => 12,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            47 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Status","table":"statuses","type":"belongsTo","column":"status_id","key":"id","label":"name","pivot_table":"commands","pivot":"0","taggable":"0"}',
                'display_name' => 'Estatus',
                'edit' => 1,
                'field' => 'command_belongsto_status_relationship',
                'id' => 49,
                'order' => 15,
                'read' => 1,
                'required' => 1,
                'type' => 'relationship',
            ),
            48 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{"scope":"rooms","model":"App\\\\Models\\\\Room","table":"rooms","type":"belongsTo","column":"room_id","key":"id","label":"name","pivot_table":"commands","pivot":"0","taggable":"0"}',
                'display_name' => 'Habitación',
                'edit' => 1,
                'field' => 'command_belongsto_room_relationship',
                'id' => 50,
                'order' => 13,
                'read' => 1,
                'required' => 0,
                'type' => 'relationship',
            ),
            49 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Room Id',
                'edit' => 1,
                'field' => 'room_id',
                'id' => 51,
                'order' => 14,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
        ));
        
        
    }
}